// Generated by Haxe 4.3.0
(function ($global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var ValueType = $hxEnums["ValueType"] = { __ename__:true,__constructs__:null
	,TNull: {_hx_name:"TNull",_hx_index:0,__enum__:"ValueType",toString:$estr}
	,TInt: {_hx_name:"TInt",_hx_index:1,__enum__:"ValueType",toString:$estr}
	,TFloat: {_hx_name:"TFloat",_hx_index:2,__enum__:"ValueType",toString:$estr}
	,TBool: {_hx_name:"TBool",_hx_index:3,__enum__:"ValueType",toString:$estr}
	,TObject: {_hx_name:"TObject",_hx_index:4,__enum__:"ValueType",toString:$estr}
	,TFunction: {_hx_name:"TFunction",_hx_index:5,__enum__:"ValueType",toString:$estr}
	,TClass: ($_=function(c) { return {_hx_index:6,c:c,__enum__:"ValueType",toString:$estr}; },$_._hx_name="TClass",$_.__params__ = ["c"],$_)
	,TEnum: ($_=function(e) { return {_hx_index:7,e:e,__enum__:"ValueType",toString:$estr}; },$_._hx_name="TEnum",$_.__params__ = ["e"],$_)
	,TUnknown: {_hx_name:"TUnknown",_hx_index:8,__enum__:"ValueType",toString:$estr}
};
ValueType.__constructs__ = [ValueType.TNull,ValueType.TInt,ValueType.TFloat,ValueType.TBool,ValueType.TObject,ValueType.TFunction,ValueType.TClass,ValueType.TEnum,ValueType.TUnknown];
var Type = function() { };
Type.__name__ = true;
Type.typeof = function(v) {
	switch(typeof(v)) {
	case "boolean":
		return ValueType.TBool;
	case "function":
		if(v.__name__ || v.__ename__) {
			return ValueType.TObject;
		}
		return ValueType.TFunction;
	case "number":
		if(Math.ceil(v) == v % 2147483648.0) {
			return ValueType.TInt;
		}
		return ValueType.TFloat;
	case "object":
		if(v == null) {
			return ValueType.TNull;
		}
		var e = v.__enum__;
		if(e != null) {
			return ValueType.TEnum($hxEnums[e]);
		}
		var c = js_Boot.getClass(v);
		if(c != null) {
			return ValueType.TClass(c);
		}
		return ValueType.TObject;
	case "string":
		return ValueType.TClass(String);
	case "undefined":
		return ValueType.TNull;
	default:
		return ValueType.TUnknown;
	}
};
var electron_renderer_IpcRenderer = require("electron").ipcRenderer;
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.__name__ = true;
haxe_ds_StringMap.prototype = {
	__class__: haxe_ds_StringMap
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
	,__class__: haxe_iterators_ArrayIterator
};
var hide_core_Ide = function() {
	this.isInitialized = false;
	hide_core_Ide.inst = this;
	hide_core_IdeConfig.init();
	this.backend = hide_core_Ide.createBackend();
	this.backend.init();
	hide_core_IdeConfig.appPath = this.backend.getAppPath();
};
hide_core_Ide.__name__ = true;
hide_core_Ide.createBackend = function() {
	return new hide_electron_ElectronBackend();
};
hide_core_Ide.main = function() {
	window.onload = function() {
		console.log("hide/core/Ide.hx:105:","🌐 Renderer process starting...");
		window.document.getElementById("system-version").textContent = "🌐 Renderer process starting...";
		var app = new hide_core_Ide();
		app.init();
	};
};
hide_core_Ide.prototype = {
	getBackend: function() {
		return this.backend;
	}
	,init: function() {
		var _gthis = this;
		if(this.isInitialized) {
			return;
		}
		console.log("hide/core/Ide.hx:72:","🚀 Hide IDE initializing...");
		this.menuSystem = new hide_modules_MenuSystem(this);
		this.menuSystem.loadFromXml();
		this.menuSystem.registerCommand("onExit",function() {
			_gthis.getBackend().quit();
		});
		this.menuSystem.registerCommand("onNewProject",function() {
			console.log("hide/core/Ide.hx:81:","📄 New Project");
		});
		this.menuSystem.registerCommand("onOpenProject",function() {
			console.log("hide/core/Ide.hx:82:","📂 Open Project");
		});
		this.menuSystem.registerCommand("onPreferences",function() {
			console.log("hide/core/Ide.hx:83:","⚙️ Preferences");
		});
		this.isInitialized = true;
		console.log("hide/core/Ide.hx:94:","✅ Hide IDE ready (stub mode).");
		window.document.getElementById("system-version").textContent = "✅ Hide IDE ready (stub mode).";
	}
	,__class__: hide_core_Ide
};
var hide_core_IdeConfig = function() { };
hide_core_IdeConfig.__name__ = true;
hide_core_IdeConfig.init = function() {
	hide_core_IdeConfig.isElectron = true;
	hide_core_IdeConfig.debugMode = true;
};
var hide_electron_ElectronBackend = function() {
	this.menuClickHandler = null;
};
hide_electron_ElectronBackend.__name__ = true;
hide_electron_ElectronBackend.prototype = {
	init: function() {
		var _gthis = this;
		console.log("hide/electron/ElectronBackend.hx:14:","[ElectronBackend] init()");
		electron_renderer_IpcRenderer.on("menu:click",function(event,data) {
			console.log("hide/electron/ElectronBackend.hx:18:","🔥🔥🔥 RAW IPC RECEIVED 🔥🔥🔥");
			console.log("hide/electron/ElectronBackend.hx:19:","Channel: menu:click");
			console.log("hide/electron/ElectronBackend.hx:20:","Data: " + JSON.stringify(data));
			console.log("hide/electron/ElectronBackend.hx:21:","Type of data: " + Std.string(Type.typeof(data)));
			if(data != null) {
				console.log("hide/electron/ElectronBackend.hx:23:","data.id: " + data.id);
				console.log("hide/electron/ElectronBackend.hx:24:","Type of id: " + Std.string(Type.typeof(data.id)));
			}
		});
		electron_renderer_IpcRenderer.on("menu:click",function(event,data) {
			if(_gthis.menuClickHandler != null && data.id != null) {
				_gthis.menuClickHandler(data.id);
			}
		});
	}
	,createMenu: function(menuData) {
		electron_renderer_IpcRenderer.send("menu:build",menuData);
	}
	,onMenuClick: function(handler) {
		this.menuClickHandler = handler;
	}
	,quit: function() {
		electron_renderer_IpcRenderer.send("app:quit");
	}
	,getAppPath: function() {
		return "./";
	}
	,__class__: hide_electron_ElectronBackend
};
var hide_modules_MenuSystem = function(ide) {
	this.ide = ide;
	this.commands = new haxe_ds_StringMap();
	console.log("hide/modules/MenuSystem.hx:19:","[MenuSystem] System created!");
};
hide_modules_MenuSystem.__name__ = true;
hide_modules_MenuSystem.prototype = {
	loadFromXml: function() {
		var _gthis = this;
		console.log("hide/modules/MenuSystem.hx:23:","[MenuSystem] Start loading menu...");
		var buildMenu = function() {
			console.log("hide/modules/MenuSystem.hx:26:","[MenuSystem] Building menu from XML...");
			var xmlEl = window.document.getElementById("mainmenu");
			if(xmlEl == null) {
				console.log("hide/modules/MenuSystem.hx:29:","[MenuSystem] ⚠️ mainmenu XML not found!");
				return;
			}
			var menuData = [];
			var _g = 0;
			var _g1 = xmlEl.children.length;
			while(_g < _g1) {
				var i = _g++;
				var item = _gthis.parseMenuItem(xmlEl.children[i]);
				console.log("hide/modules/MenuSystem.hx:36:","[MenuSystem] Parsed item: label='" + item.label + "', id='" + item.id + "'");
				menuData.push(item);
			}
			console.log("hide/modules/MenuSystem.hx:40:","[MenuSystem] 📤 Sending to Main: " + JSON.stringify(menuData));
			_gthis.ide.getBackend().createMenu(menuData);
			_gthis.ide.getBackend().onMenuClick($bind(_gthis,_gthis.handleCommand));
		};
		var readyState = window.document.readyState;
		if(readyState == "complete" || readyState == "interactive") {
			buildMenu();
		} else {
			window.document.addEventListener("DOMContentLoaded",function(_) {
				buildMenu();
			});
		}
	}
	,registerCommand: function(id,handler) {
		this.commands.h[id] = handler;
	}
	,handleCommand: function(id) {
		if(Object.prototype.hasOwnProperty.call(this.commands.h,id)) {
			console.log("hide/modules/MenuSystem.hx:59:","[MenuSystem] ▶ Executing: " + id);
			this.commands.h[id]();
		} else {
			console.log("hide/modules/MenuSystem.hx:62:","[MenuSystem] ⚠️ Unknown command: " + id);
		}
	}
	,parseMenuItem: function(el) {
		var item = { label : el.getAttribute("label") != null ? el.getAttribute("label") : "Item", id : el.getAttribute("onclick"), type : el.getAttribute("type")};
		if(el.children != null && el.children.length > 0) {
			var submenu = [];
			var _g = 0;
			var _g1 = el.children.length;
			while(_g < _g1) {
				var i = _g++;
				submenu.push(this.parseMenuItem(el.children[i]));
			}
			item.submenu = submenu;
		}
		return item;
	}
	,__class__: hide_modules_MenuSystem
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if(o == null) {
		return null;
	} else if(((o) instanceof Array)) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var con = e.__constructs__[o._hx_index];
			var n = con._hx_name;
			if(con.__params__) {
				s = s + "\t";
				return n + "(" + ((function($this) {
					var $r;
					var _g = [];
					{
						var _g1 = 0;
						var _g2 = con.__params__;
						while(true) {
							if(!(_g1 < _g2.length)) {
								break;
							}
							var p = _g2[_g1];
							_g1 = _g1 + 1;
							_g.push(js_Boot.__string_rec(o[p],s));
						}
					}
					$r = _g;
					return $r;
				}(this))).join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
Object.defineProperty(String.prototype,"__class__",{ value : String, enumerable : false, writable : true});
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
hide_core_IdeConfig.appPath = "";
hide_core_IdeConfig.isElectron = false;
hide_core_IdeConfig.debugMode = false;
hide_core_Ide.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=app.js.map